data:
    dataset: "PMUB"
    train_dataroot: "data/LD_FD_CT_train"
    val_dataroot: "data/PMUB-val"
    sample_dataroot: "data/LD_FD_CT_test"
    image_size: 256
    channels: 1
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: true
    rescaled: true
    num_workers: 8

model:
    type: "sg"
    in_channels: 2
    out_ch: 1
    ch: 128
    ch_mult: [1, 1, 2, 2, 4, 4]
    num_res_blocks: 2
    attn_resolutions: [16,]
    dropout: 0.0
    var_type: fixedsmall
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000

training:
    batch_size: 16
    n_epochs: 10000
    n_iters: 5000000
    snapshot_freq: 100000
    validation_freq: 5000000000

sampling:
    batch_size: 8
    ckpt_id: [100000, 200000, 300000, 400000, 500000, 600000, 700000, 800000, 900000, 1000000, 1500000, 2000000]
    last_only: True

sampling_inter:
    batch_size: 59
    last_only: True

sampling_fid:
    batch_size: 128
    last_only: True

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.00002
    beta1: 0.9
    amsgrad: false
    eps: 0.00000001
